app_pet:
    path: /
    controller: App\Controller\PetController::index




app_display:
    path: /display/{id}
    controller: App\Controller\PetController::display


app_family:
    path: /family
    controller: App\Controller\FamilyController::index




app_continents:
    path: /continents
    controller: App\Controller\ContinentsController::displayListContinents


  

  